In [80]:
# Load IRIS data set using the PDS GITHUB Repository.
# Using Pandas, numpy and Array manipulation techniques to
# create a 3D array splitting on any three columns of the
#dataset.

import pandas as pd
import numpy as np

IrisDS = pd.read_csv("https://raw.githubusercontent.com/colaberry/Practical-Data-Science/master/Datasets/IRIS/iris.csv")
IrisDS.head(50)

A1=np.array(IrisDS.iloc[:3,:3])
A2=np.array(IrisDS.iloc[4:7,1:4])
A3=np.array(IrisDS.iloc[8:11,1:4])

#print(A1)
#print(A2)
#print(A3)

x=np.array(np.atleast_3d(A1,A2,A3))
print(x.shape)
print(x)


(3, 3, 3, 1)
[[[[5.1]
   [3.5]
   [1.4]]

  [[4.9]
   [3. ]
   [1.4]]

  [[4.7]
   [3.2]
   [1.3]]]


 [[[3.6]
   [1.4]
   [0.2]]

  [[3.9]
   [1.7]
   [0.4]]

  [[3.4]
   [1.4]
   [0.3]]]


 [[[2.9]
   [1.4]
   [0.2]]

  [[3.1]
   [1.5]
   [0.1]]

  [[3.7]
   [1.5]
   [0.2]]]]
