In [3]:
#numpy exercises

# #. Find indices of non-zero elements from [1,2,0,0,4,0]

import numpy as np
print(np.nonzero([1,2,0,0,4,0]))



(array([0, 1, 4], dtype=int64),)


In [9]:
# Create a null vector of size 10 
#print(np.arange(Null,10))

z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# Create a null vector of size 10 but the fifth value which is 1

#z=np.insert(np.zero(10),4,1)
import numpy as np
z=np.zeros(10)
z[4] =1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
# Create a vector with values ranging from 10 to 49 
v=np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [39]:
#Reverse a vector (first element becomes last)
k=np.arange(50)
print(k[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [59]:
# Create a 3x3 matrix with values ranging from 0 to 8
#np.info(np.matrix)

#np.info(np.matrix)

print(np.matrix([[0,1,2],[3,4,5],[6,7,8]]))

z=np.arange(9).reshape(3,3)
z
#Z = np.arange(9).reshape(3,3)
#print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [77]:
#Create a 3x3 identity matrix 
i = np.zeros(9).reshape(3,3)
i[0,0]=i[1,1]=i[2,2]=1
i

###########

idn = np.eye(4)
idn

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
# Create a 3x3x3 array with random values 
r = np.random.random((3,3,3))
r

array([[[0.66243625, 0.65117782, 0.42645575],
        [0.76152671, 0.3610236 , 0.37783188],
        [0.59857725, 0.84608249, 0.70590809]],

       [[0.5225078 , 0.09353346, 0.0676774 ],
        [0.32801691, 0.41620317, 0.32287295],
        [0.62796007, 0.18044885, 0.88155202]],

       [[0.50098503, 0.57859818, 0.03380243],
        [0.54029566, 0.63459235, 0.24938663],
        [0.11151219, 0.09874653, 0.7219474 ]]])

In [136]:
# Create a 10x10 array with random values and find the minimum and maximum values
#np.info(np.random)

z=np.random.random((10,10))
z.min()
z.max()


0.9941431176363468

In [142]:
# Create a random vector of size 30 and find the mean value 

rv=np.random.random((30))
rv
rv.mean()


0.4640903865593454

In [155]:
# 14.Create a 2d array with 1 on the border and 0 inside

#dr = np.ones((3,3))
#dr[1,1]=0
#dr

########################

c = np.ones((10,10))
#Z[1:-1,1:-1] = 0
c[1:-1,1:-1]=0
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [159]:
# what is the result of following expression

0 * np.nan
np.nan == np.nan
print(np.nan)

print(np.inf)
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

nan
inf


False

In [166]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

#np.info(np.matrix)

# Z = np.diag(1+np.arange(4),k=-1)

np.diag(1+np.arange(4),k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [178]:
# Create a 8x8 matrix and fill it with a checkerboard pattern 
np.random.randint(shape=(8,8))

TypeError: randint() takes at least 1 positional argument (0 given)